// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxEB08qi8XJJOU6DHBrM9sFEiA-Rgerp0',
    appId: '1:355567000935:android:72ce94a86f91cad717e3c2',
    messagingSenderId: '355567000935',
    projectId: 'fish-934cd',
    storageBucket: 'fish-934cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx0yNNGqSFwJKKVdzh-Au6lHQnCu2mLy8',
    appId: '1:355567000935:ios:14729cc6fa73d0ba17e3c2',
    messagingSenderId: '355567000935',
    projectId: 'fish-934cd',
    storageBucket: 'fish-934cd.firebasestorage.app',
    androidClientId: '355567000935-pjaqff8l7fv5dcq6sa6e9okpa8hkci99.apps.googleusercontent.com',
    iosClientId: '355567000935-8bv16ijuecic67vlukvmirl6n2uquep1.apps.googleusercontent.com',
    iosBundleId: 'com.example.fishSpeciesIdentifier',
  );

}